# Generated by Django 6.0.3 on 2026-06-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Upload a project screenshot.', null=True, upload_to='projects/')),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies (e.g., Django, Python, MySQL, HTML)', max_length=500)),
                ('github_link', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('live_link', models.URLField(blank=True, help_text='Live demo URL', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers show first)')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
